name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run start script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            cd /app/nutrition-calculator
            pwd
            git checkout main
            git stash
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            killall -9 node
            nohup npm run dev 1>/dev/null 2>&1 &
