name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/cache@v2
#        with:
#          path: '**/node_modules'
#          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#      - name: Install Dependencies
#        run: yarn install
#      - name: Build
#        run: yarn build
#      - name: Compress into a zip file # S3에 올릴 zip 파일 생성. (빌드한 프로젝트를 압축)
#        run: zip -qq -r ./app.zip .
#      - name: Transfer jar file
#        uses: appleboy/scp-action@v0.1.4
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: 22
#          source: "app.zip"
#          target: "/app/nutrition-calculator"
      - name: Run start script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            cd /app/nutrition-calculator
            pwd
            git checkout main
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            killall -9 node
            nohup npm run dev 1>/dev/null 2>&1 &
